import { Inter } from "next/font/google";
import StoreProvider from "@/state_management/StoreProvider";
import AuthenticationProvider from "@/app/AuthenticatedProvider";
import ModalRoot from "@/components/modal/ModalRoot";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <StoreProvider>
          <AuthenticationProvider>
            {children}
            <ModalRoot />
          </AuthenticationProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
